package org.krmdemo.techlabs.ghapi;

import com.fasterxml.jackson.annotation.JsonProperty;
import feign.RequestLine;
import org.krmdemo.techlabs.core.datetime.DateTimeTriplet;

import java.time.Duration;
import java.util.Map;

/**
 * This interface represents a facade to GitHub-API, which should be instantiated via {@link Factory}
 */
public interface GithubApi {

    /**
     * A root URL to access GitHub-API via REST (where the REST is just HTTP + JSON)
     */
    String URL_GITHUB_API = "https://api.github.com";

    /**
     * The default HTTP-timeout for each remote REST-request
     */
    Duration HTTP_TIMEOUT = Duration.ofSeconds(5);

    // ---------------------------------------------------------------------------------------------

    /**
     * This Java-record represents basic properties of GitHub-API entity {@code user} / {@code owner},
     * which owns multiple-repositories that are represented by {@link Repository}.
     * <hr/>
     * Any GitHub-repository is identified by GitHub-{@code owner}'s name and GitHub-{@code repository}'s name,
     * but could GitHub-API also uses the ID of user/owner (in most cases the login is enough because it's unique globally).
     *
     * @param id a unique ID that is generated by GitHub and identifies each user GitHub-{@code user}
     * @param login a login of GitHub-{@code user} and a name of corresponding GitHUb-{@code owner}
     * @param createdAt the date-time when GitHub-{@code user} was created
     * @param updatedAt the last date-time when GitHub-{@code user} was updated
     */
    record User(
        String id,
        String login,
        @JsonProperty("created_at") DateTimeTriplet createdAt,
        @JsonProperty("updated_at") DateTimeTriplet updatedAt
    ) {}

    /**
     * Feign-Interface to access GitHub-API to
     */
    interface UserClient {

        /**
         * Loading the basic properties of GitHub-{@code user} that corresponds to GitHub-{@code token} in HTTP-header
         *
         * @return the basic properties of GitHub-{@code user} as {@link User}
         */
        @RequestLine("GET /user")
        User getUser();

        /**
         * Loading all properties of GitHub-{@code user} that corresponds to GitHub-{@code token} in HTTP-header
         *
         * @return all properties of GitHub-{@code user} as JSON-object, which is represented by {@link Map Map&lt;String,Object&gt;}
         */
        @RequestLine("GET /user")
        Map<String, Object> getUserProps();
    }

    /**
     * Getting the implementation of {@link UserClient} that corresponds to GitHub-{@code token},
     * which is provided via {@link Factory#githubToken(String)}
     *
     * @return the implementation of {@link UserClient}
     */
    UserClient userClient();

    /**
     * A shortcut to {@code userClient().getUser()}
     *
     * @return the basic properties of GitHub-{@code user} that corresponds to GitHub-{@code token} in HTTP-header
     */
    User currentUser();

    // ---------------------------------------------------------------------------------------------

    /**
     * This Java-record represents basic properties of GitHub-API entity {@code repository}.
     * <hr/>
     * Any GitHub-repository is identified by GitHub-{@code owner}'s name and GitHub-{@code repository}'s name,
     * but GitHub-API also uses the ID of repository to access packages, workflows, etc.
     *
     * @param id a unique ID that is generated by GitHub and identifies any GitHub-{@code repository} uniquely
     * @param name a name of GitHub-{@code repository}, which is unique only within concrete GitHub-{@code owner}
     * @param createdAt the date-time when GitHub-{@code repository} was created
     * @param updatedAt the last date-time when GitHub-{@code repository} was updated
     */
    record Repository(
        String id,
        String name,
        @JsonProperty("created_at") DateTimeTriplet createdAt,
        @JsonProperty("updated_at") DateTimeTriplet updatedAt
    ) {}

    // ---------------------------------------------------------------------------------------------

    static Factory feignFactory() {
        return new GithubApiFeign.FactoryImpl();
    }

    abstract class Factory {
        String githubToken;
        String ownerName;
        String repoName;

        public abstract GithubApi create();

        public Factory githubToken(String githubToken) {
            this.githubToken = githubToken;
            return this;
        }

        public Factory ownerName(String ownerName) {
            this.ownerName = ownerName;
            return this;
        }

        public Factory repoName(String repoName) {
            this.repoName = ownerName;
            return this;
        }
    }
}
