package org.krmdemo.techlabs.ghapi;

import com.fasterxml.jackson.annotation.JsonProperty;
import feign.Param;
import feign.RequestLine;
import org.krmdemo.techlabs.core.datetime.DateTimeTriplet;

import java.time.Duration;
import java.util.Map;

/**
 * This interface represents a facade to GitHub-API, which should be instantiated via {@link Factory}
 */
public interface GithubApi {

    /**
     * A root URL to access GitHub-API via REST (where the REST is just HTTP + JSON)
     */
    String URL_GITHUB_API = "https://api.github.com";

    /**
     * The default HTTP-timeout for each remote REST-request
     */
    Duration HTTP_TIMEOUT = Duration.ofSeconds(5);

    // ---------------------------------------------------------------------------------------------

    /**
     * This Java-record represents basic properties of GitHub-API entity {@code user} / {@code owner},
     * which owns multiple-repositories that are represented by {@link Repository}.
     * <hr/>
     * Any GitHub-repository is identified by GitHub-{@code owner}'s name and GitHub-{@code repository}'s name,
     * but could GitHub-API also uses the ID of user/owner (in most cases the login is enough because it's unique globally).
     *
     * @param id a unique ID that is generated by GitHub and identifies each user GitHub-{@code user}
     * @param login a login of GitHub-{@code user} and a name of corresponding GitHUb-{@code owner}
     * @param type either the value "User" or "Organization"
     * @param createdAt the date-time when GitHub-{@code user} was created
     * @param updatedAt the last date-time when GitHub-{@code user} was updated
     */
    record User(
        String id,
        String login,
        String type,
        @JsonProperty("created_at") DateTimeTriplet createdAt,
        @JsonProperty("updated_at") DateTimeTriplet updatedAt
    ) {}

    /**
     * Feign-Interface to access GitHub-API to
     */
    interface UserClient {

        /**
         * Loading the basic properties of GitHub-{@code user} that corresponds to GitHub-{@code token} in HTTP-header
         *
         * @return the basic properties of GitHub-{@code user} as {@link User}
         */
        @RequestLine("GET /user")
        User getUser();

        /**
         * Loading all properties of GitHub-{@code user} that corresponds to GitHub-{@code token} in HTTP-header
         *
         * @return all properties of GitHub-{@code user} as JSON-object, which is represented by {@link Map Map&lt;String,Object&gt;}
         */
        @RequestLine("GET /user")
        Map<String, Object> getUserProps();


        /**
         * Loading the basic properties of GitHub-{@code owner} with passed {@code ownerName}.
         *
         * @param ownerName a name of owner, which is the same as {@link User#login()}
         *                  (if the repository belong to GitHub-{@code user})
         *                  or the name of GitHub-{@code organization}
         *                  - anyway, this property corresponds to the first part of GitHub-repository's full name
         * @return an owner of repository as {@link User}
         */
        @RequestLine("GET /users/{ownerName}")
        User getOwner(@Param("ownerName") String ownerName);
    }

    /**
     * Getting the implementation of {@link UserClient} that corresponds to GitHub-{@code token},
     * which is provided via {@link Factory#githubToken(String)}
     *
     * @return the implementation of {@link UserClient}
     */
    UserClient userClient();

    /**
     * A shortcut to {@code userClient().getUser()}
     *
     * @return the basic properties of GitHub-{@code user} as {@link User}
     */
    User currentUser();

    // ---------------------------------------------------------------------------------------------

    /**
     * This Java-record represents basic properties of GitHub-API entity {@code repository}.
     * <hr/>
     * Any GitHub-repository is identified by GitHub-{@code owner}'s name and GitHub-{@code repository}'s name,
     * but GitHub-API also uses the ID of repository to access packages, workflows, etc.
     *
     * @param id a unique ID that is generated by GitHub and identifies any GitHub-{@code repository} uniquely
     * @param name a name of GitHub-{@code repository}, which is unique only within concrete GitHub-{@code owner}
     * @param createdAt the date-time when GitHub-{@code repository} was created
     * @param updatedAt the last date-time when GitHub-{@code repository} was updated
     */
    record Repository(
        String id,
        String name,
        String description,
        @JsonProperty("full_name") String fullName,
        @JsonProperty("html_url") String htmlUrl,
        @JsonProperty("clone_url") String cloneUrl,
        @JsonProperty("created_at") DateTimeTriplet createdAt,
        @JsonProperty("updated_at") DateTimeTriplet updatedAt,
        @JsonProperty("pushed_at") DateTimeTriplet pushedAt
    ) {}

    /**
     * Feign-Interface to access GitHub-API to
     */
    interface RepositoryClient {

        /**
         * Loading the basic properties of GitHub-{@code repository} by the first and the second parts
         * of full name (slash{@code '/'}-separated {@code ownerName} and {@code repoName})
         *
         * @param ownerName the first part of {@link Repository#fullName()}, which corresponds to {@link User#login()}
         * @param repoName the second part of {@link Repository#fullName()}, which is just a name of GitHib-{@code repository}
         * @return the basic properties of GitHub-{@code repository} as {@link Repository}
         */
        @RequestLine("GET /repos/{ownerName}/{repoName}")
        Repository getRepository(
            @Param("ownerName") String ownerName,
            @Param("repoName") String repoName
        );
    }

    /**
     * Getting the implementation of {@link UserClient} that corresponds to GitHub-{@code token},
     * which is provided via {@link Factory#githubToken(String)}
     *
     * @return the implementation of {@link UserClient}
     */
    RepositoryClient repositoryClient();



    // ---------------------------------------------------------------------------------------------

    static Factory feignFactory() {
        return new GithubApiFeign.FactoryImpl();
    }

    abstract class Factory {
        String githubToken;
        String ownerName;
        String repoName;

        public abstract GithubApi create();

        public Factory githubToken(String githubToken) {
            this.githubToken = githubToken;
            return this;
        }

        public Factory ownerName(String ownerName) {
            this.ownerName = ownerName;
            return this;
        }

        public Factory repoName(String repoName) {
            this.repoName = ownerName;
            return this;
        }
    }
}
