package org.krmdemo.techlabs.ghapi;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import feign.Param;
import feign.QueryMap;
import feign.RequestLine;
import lombok.Setter;
import lombok.experimental.Accessors;
import org.apache.commons.lang3.concurrent.ConcurrentException;
import org.krmdemo.techlabs.core.datetime.DateTimeTriplet;

import java.time.Duration;
import java.util.Collection;
import java.util.Map;
import java.util.NavigableMap;
import java.util.Optional;

/**
 * This interface represents a facade to GitHub-API, which should be instantiated via {@link Factory}
 */
public interface GithubApi {

    /**
     * A root URL to access GitHub-API via REST (where the REST is just HTTP + JSON)
     */
    String URL_GITHUB_API = "https://api.github.com";

    /**
     * The default HTTP-timeout for each remote REST-request
     */
    Duration HTTP_TIMEOUT = Duration.ofSeconds(5);

    // ---------------------------------------------------------------------------------------------

    /**
     * This Java-record represents basic properties of GitHub-API entity {@code user} / {@code owner},
     * which owns multiple-repositories that are represented by {@link Repository}.
     * <hr/>
     * Any GitHub-repository is identified by GitHub-{@code owner}'s name and GitHub-{@code repository}'s name,
     * but could GitHub-API also uses the ID of user/owner (in most cases the login is enough because it's unique globally).
     *
     * @param id a unique ID that is generated by GitHub and identifies each user GitHub-{@code user}
     * @param login a login of GitHub-{@code user} and a name of corresponding GitHUb-{@code owner}
     * @param type either the value "User" or "Organization"
     * @param createdAt the date-time when GitHub-{@code user} was created
     * @param updatedAt the last date-time when GitHub-{@code user} was updated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    record User(
        String id,
        String login,
        String type,
        @JsonProperty("created_at") DateTimeTriplet createdAt,
        @JsonProperty("updated_at") DateTimeTriplet updatedAt
    ) {}

    /**
     * Feign-Interface to access GitHub-API for GitHub-entities of type {@link User}
     */
    interface UserClient {

        /**
         * Loading the basic properties of GitHub-{@code user} that corresponds to GitHub-{@code token} in HTTP-header
         *
         * @return the basic properties of GitHub-{@code user} as {@link User}
         */
        @RequestLine("GET /user")
        User getUser();

        /**
         * Loading all properties of GitHub-{@code user} that corresponds to GitHub-{@code token} in HTTP-header
         *
         * @return all properties of GitHub-{@code user} as JSON-object, which is represented by {@link Map Map&lt;String,Object&gt;}
         */
        @RequestLine("GET /user")
        Map<String, Object> getUserProps();

        /**
         * Loading the basic properties of GitHub-{@code owner} with passed {@code ownerName}.
         *
         * @param ownerName a name of owner, which is the same as {@link User#login()}
         *                  (if the repository belong to GitHub-{@code user})
         *                  or the name of GitHub-{@code organization}
         *                  - anyway, this property corresponds to the first part of GitHub-repository's full name
         * @return an owner of repository as {@link User}
         */
        @RequestLine("GET /users/{ownerName}")
        User getOwner(@Param("ownerName") String ownerName);
    }

    /**
     * Getting the implementation of {@link UserClient} that corresponds to GitHub-{@code token},
     * which is provided via {@link Factory#githubToken(String)}
     *
     * @return the implementation of {@link UserClient}
     */
    UserClient userClient();

    /**
     * A shortcut to {@link #userClient() userClient()}{@link UserClient#getUser() .getUser()},
     * but the result is expected to be cached by implementation to avoid redundant REST-invocations.
     *
     * @return the basic properties of GitHub-{@code user} as {@link User}
     */
    User getCurrentUser();

    // ---------------------------------------------------------------------------------------------

    /**
     * This Java-record represents basic properties of GitHub-API entity {@code repository}.
     * <hr/>
     * Any GitHub-repository is identified by GitHub-{@code owner}'s name and GitHub-{@code repository}'s name,
     * but GitHub-API also uses the ID of repository to access packages, workflows, etc.
     *
     * @param id a unique ID that is generated by GitHub and identifies any GitHub-{@code repository} uniquely
     * @param name a name of GitHub-{@code repository}, which is unique only within concrete GitHub-{@code owner}
     * @param createdAt the date-time when GitHub-{@code repository} was created
     * @param updatedAt the last date-time when GitHub-{@code repository} was updated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    record Repository(
        String id,
        String name,
        String description,
        @JsonProperty("full_name") String fullName,
        @JsonProperty("html_url") String htmlUrl,
        @JsonProperty("clone_url") String cloneUrl,
        @JsonProperty("created_at") DateTimeTriplet createdAt,
        @JsonProperty("updated_at") DateTimeTriplet updatedAt,
        @JsonProperty("pushed_at") DateTimeTriplet pushedAt
    ) {}

    /**
     * Feign-Interface to access GitHub-API for GitHub-entities of type {@link Repository}
     */
    interface RepositoryClient {

        /**
         * Loading the basic properties of GitHub-{@code repository} by the first and the second parts
         * of the full name (slash{@code '/'}-separated {@code ownerName} and {@code repoName})
         *
         * @param ownerName the first part of {@link Repository#fullName()}, which corresponds to {@link User#login()}
         * @param repoName the second part of {@link Repository#fullName()}, which is just a name of GitHib-{@code repository}
         * @return the basic properties of GitHub-{@code repository} as {@link Repository}
         */
        @RequestLine("GET /repos/{ownerName}/{repoName}")
        Repository getRepository(
            @Param("ownerName") String ownerName,
            @Param("repoName") String repoName
        );

        /**
         * Loading all properties of GitHub-{@code repository} by the first and the second parts
         * of the full name (slash{@code '/'}-separated {@code ownerName} and {@code repoName})
         *
         * @param ownerName the first part of {@link Repository#fullName()}, which corresponds to {@link User#login()}
         * @param repoName the second part of {@link Repository#fullName()}, which is just a name of GitHib-{@code repository}
         * @return all properties of GitHub-{@code repository} as JSON-object, which is represented by {@link Map Map&lt;String,Object&gt;}
         */
        @RequestLine("GET /repos/{ownerName}/{repoName}")
        Map<String, Object> getRepoProps(
            @Param("ownerName") String ownerName,
            @Param("repoName") String repoName
        );

        /**
         * Loading the collection of GitHub-{@code repositories} that belong to the current user,
         * which corresponds to GitHub-{@code token} in HTTP-header.
         *
         * @return the collection of GitHub-{@code repositories} for the {@link #getCurrentUser() current user}
         */
        @RequestLine("GET /user/repos")
        Collection<Repository> getUserRepos();

        /**
         * Loading the collection of GitHub-{@code repositories} that belong to the GitHub-{@code user}
         * or GitHub-{@code organization} with the passed {@code ownerName}.
         *
         * @return the collection of GitHub-{@code repositories} for the owner with the passed {@code ownerName}
         */
        @RequestLine("GET /users/{ownerName}/repos")
        Collection<Repository> getOwnerRepos(@Param("ownerName") String ownerName);
    }

    /**
     * Getting the implementation of {@link RepositoryClient} that corresponds to GitHub-{@code token},
     * which is provided via {@link Factory#githubToken(String)}
     *
     * @return the implementation of {@link RepositoryClient}
     */
    RepositoryClient repositoryClient();

    /**
     * Getting the sorted map over the result of {@link RepositoryClient#getUserRepos()}
     *
     * @return a sorted map over the collection of GitHub-{@code repositories} of the {@link #getCurrentUser() current user},
     *         where the {@link Map.Entry#getKey() key} is repository's {@link Repository#name() name}
     *         and the {@link Map.Entry#getValue() value} is a basic repository properties as {@link Repository}
     */
    NavigableMap<String, Repository> currentUserReposMap();

    /**
     * Getting the sorted map over the result of {@link RepositoryClient#getOwnerRepos(String)}
     *
     * @param ownerName the first part of {@link Repository#fullName()}, which also corresponds to {@link User#login()}
     * @return a sorted map over the collection of GitHub-{@code repositories} of the GitHub-{@code owner}
     *         with the passed {@code ownerName}, where the {@link Map.Entry#getKey() key} is repository's {@link Repository#name() name}
     *         and the {@link Map.Entry#getValue() value} is a basic repository properties as {@link Repository}
     */
    NavigableMap<String, Repository> ownerReposMap(String ownerName);

    /**
     * Loading the basic properties of the current GitHub-{@code repository} as {@link Repository},
     * whose {@link Repository#fullName()} corresponds to values that was passed to {@link Factory#ownerName(String)}
     * and to {@link Factory#repoName(String)} accordingly.
     * <hr/>
     * The result is expected to be cached by implementation to avoid redundant REST-invocations.
     * This method is the most important of the whole GitHub-API that allows to get the ID of the current repository.
     *
     * @return the basic properties of the current repository as {@link Repository}
     */
    Repository getCurrentRepo();

    /**
     * Loading all the properties of the current GitHub-{@code repository}
     * as JSON-object, which is represented by {@link Map Map&lt;String,Object&gt;},
     * whose {@link Repository#fullName()} corresponds to values that was passed to {@link Factory#ownerName(String)}
     * and to {@link Factory#repoName(String)} accordingly.
     * <hr/>
     * The most important method of the whole GitHub-API that allows to get the ID of the current repository
     *
     * @return all the properties of the current GitHub-{@code repository}
     *         as JSON-object, which is represented by {@link Map Map&lt;String,Object&gt;}
     */
    Map<String, Object> currentRepoProps();

    // ---------------------------------------------------------------------------------------------

    /**
     * This Java-record represents basic properties of GitHub-API entity {@code package}.
     *
     * @param id a unique ID that is generated by GitHub and identifies any GitHub-{@code package} uniquely
     * @param name a name of GitHub-{@code package}, which is dot{@code '.'}-separated maven-group and maven-artifact
     * @param createdAt the date-time when GitHub-{@code package} was created
     * @param updatedAt the last date-time when GitHub-{@code package} was updated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    record Package(
        String id,
        String name,
        Repository repository,
        @JsonProperty("package_type") String packageType,
        @JsonProperty("version_count") Integer versionCount,
        @JsonProperty("html_url") String htmlUrl,
        @JsonProperty("created_at") DateTimeTriplet createdAt,
        @JsonProperty("updated_at") DateTimeTriplet updatedAt
    ) {}

    /**
     * Feign-Interface to access GitHub-API for GitHub-entities of type {@link Package}
     */
    interface PackageClient {

        /**
         * Loading the collection of GitHub-{@code packages} of type {@code "maven"} that belong to the current user,
         * which corresponds to GitHub-{@code token} in HTTP-header.
         *
         * @return the collection of GitHub-{@code packages} of type {@code "maven"} for the {@link #getCurrentUser() current user}
         */
        @RequestLine("GET /user/packages")
        Collection<Package> getUserMavenPackages();

        /**
         * Loading the collection of GitHub-{@code packages} that belong to the GitHub-{@code user}
         * or GitHub-{@code organization} with the passed {@code ownerName}.
         *
         * @param ownerName the first part of {@link Repository#fullName()}, which also corresponds to {@link User#login()}
         * @return the collection of GitHub-{@code packages} of type {@code "maven"} for the owner with the passed {@code ownerName}
         */
        @RequestLine("GET /users/{ownerName}/packages")
        Collection<Package> getOwnerMavenPackages(@Param("ownerName") String ownerName);
    }

    /**
     * Getting the implementation of {@link PackageClient} that corresponds to GitHub-{@code token},
     * which is provided via {@link Factory#githubToken(String)}
     *
     * @return the implementation of {@link PackageClient}
     */
    PackageClient packageClient();

    NavigableMap<String, Package> userMavenPackagesMap();

    NavigableMap<String, Package> ownerMavenPackagesMap(String ownerName);

    NavigableMap<String, NavigableMap<String, Package>> userRepoToMavenPackages();

    NavigableMap<String, NavigableMap<String, Package>> ownerRepoToMavenPackages(String ownerName);

    Optional<Package> getCurrentRepoMavenPkgOpt();

    default boolean isCurrentRepoMavenPkgPresent() {
        return getCurrentRepoMavenPkgOpt().isPresent();
    }

    default Package getCurrentRepoMavenPkg() {
        return getCurrentRepoMavenPkgOpt().orElse(null);
    }

    // ---------------------------------------------------------------------------------------------

    /**
     * This Java-record represents basic properties of GitHub-API entity {@code package-version}.
     *
     * @param id a unique ID that is generated by GitHub and identifies any GitHub-{@code package-version} uniquely
     * @param name a name of GitHub-{@code package-version}, which corresponds maven-project version
     * @param createdAt the date-time when GitHub-{@code package-version} was created
     * @param updatedAt the last date-time when GitHub-{@code package-version} was updated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    record PkgVer(
        String id,
        String name,
        String license,
        @JsonProperty("html_url") String htmlUrl,
        @JsonProperty("created_at") DateTimeTriplet createdAt,
        @JsonProperty("updated_at") DateTimeTriplet updatedAt
    ) {}

    /**
     * Feign-Interface to access GitHub-API for GitHub-entities of type {@link PkgVer}
     */
    interface PkgVerClient {

        /**
         * Loading the collection of the last not more than {@code 30} <b>active</b> versions for GitHub-{@code package}
         * with the given {@code packageName} of type {@code "maven"} that belong to the current user
         * (whose GitHub-{@code token} is passed in HTTP-header).
         * <hr/>
         * To get more versions of the given package the method {@link #userMavenPackageVersions} should be used,
         * which returns a paging-result as {@link PagingResult} of {@link PkgVer}.
         * <hr/>
         * The default maximum value {@code 30} is the current limitation of GitHub-API.
         *
         * @param packageName a name of GitHub-{@code package}, which corresponds to {@link Package#name()}
         * @return the collection of the last not more than {@code 30} items of type {@link PkgVer}
         */
        @RequestLine("GET /user/packages/maven/{packageName}/versions")
        Collection<PkgVer> getUserMavenPackageVersions(
            @Param("packageName") String packageName
        );

        /**
         * The same as {@link #getUserMavenPackageVersions(String)}, but for any owner.
         *
         * @param ownerName the first part of {@link Repository#fullName()}, which also corresponds to {@link User#login()}
         * @param packageName a name of GitHub-{@code package}, which corresponds to {@link Package#name()}
         * @return the collection of the last not more than {@code 30} items of type {@link PkgVer}
         */
        @RequestLine("GET /users/{ownerName}/packages/maven/{packageName}/versions")
        Collection<PkgVer> getOwnerMavenPackageVersions(
            @Param("ownerName") String ownerName,
            @Param("packageName") String packageName
        );

        /**
         * Getting the paging-result with the list of versions for GitHub-{@code package}
         * with the given {@code packageName} of type {@code "maven"} that belong to the current user
         * (whose GitHub-{@code token} is passed in HTTP-header).
         * <hr/>
         * The parameter {@code queryMap} is expected to contain following entries:<ul>
         *     <li>{@code page} - the number of the page that is started from {@code 1}
         *     (the default value is {@code 1})</li>
         *     <li>{@code per_page} - the size of each page (maybe except the last one), which must not be greater than {@code 100}
         *     (the default value is {@code 30})</li>
         *     <li>{@code state} - either {@code "active"} of {@code "deleted"} for the status of fetched versions accordingly
         *     (the default value is {@code "active"})</li>
         * </ul>
         * The maximum page-size {@code 100} is the current limitation of GitHub-API.
         *
         * @param packageName a name of GitHub-{@code package}, which corresponds to {@link Package#name()}
         * @param queryMap the parameters of HTTP-query with entries described above
         * @return the paging-result as {@link PagingResult} of {@link PkgVer}
         *
         * @see <a href="https://docs.github.com/en/rest/packages/packages?apiVersion=2022-11-28#get-a-package-version-for-the-authenticated-user">
         *     (GitHub-API docs) List package versions for a package owned by the authenticated user
         * </a>
         */
        @RequestLine("GET /user/packages/maven/{packageName}/versions")
        PagingResult<PkgVer> userMavenPackageVersions(
            @Param("packageName") String packageName,
            @QueryMap Map<String, Object> queryMap
        );
    }

    /**
     * Getting the implementation of {@link PkgVerClient} that corresponds to GitHub-{@code token},
     * which is provided via {@link Factory#githubToken(String)}
     *
     * @return the implementation of {@link PackageClient}
     */
    PkgVerClient pkgVerClient();

    /**
     * Getting the number of <b>active</b> versions for GitHub-{@code package} with the given {@code packageName}.
     * The result of this invocation must equal to the value of {@link Package#versionCount()},
     * but it's calculated via GitHub-API paging.
     *
     * @param packageName a name of GitHub-{@code package}, which corresponds to {@link Package#name()}
     * @return the number of versions for GitHub-{@code package} with the given {@code packageName}
     */
    int userMavenPackageVersionsCount(String packageName);

    // ---------------------------------------------------------------------------------------------

    /**
     * Getting the instance of {@link Factory} that produces the instances of {@link GithubApi},
     * which is based on using <a href="https://github.com/OpenFeign/feign">Open-Feign</a>.
     *
     * @return feign-based {@link Factory} to produce the instances of {@link GithubApi}
     */
    static Factory feignFactory() {
        return new GithubApiFeign.FactoryImpl();
    }

    /**
     * This class represents a factory to produce the instances of {@link GithubApi}
     *
     * @see <a href="https://www.digitalocean.com/community/tutorials/builder-design-pattern-in-java">
     *     Builder Design Pattern in Java
     * </a>
     * @see <a href="https://www.baeldung.com/java-builder-pattern">
     *     Implement the Builder Pattern in <code>Java</code>
     * </a>
     */
    @Setter
    @Accessors(fluent = true, chain = true)
    abstract class Factory {
        protected String githubToken;
        protected String ownerName;
        protected String repoName;
        protected String mavenProjectGroup;
        protected String mavenProjectArtifact;
        protected String mavenPackageName;

        /**
         * Creating the instance of {@link GithubApi} according to concrete implementation of this {@link Factory}.
         * Possible approaches could be based on:<ul>
         *     <li>using the direct HTTP-client (either from JDK or third-party like <a href="https://square.github.io/okhttp/">OkHttp</a>);</li>
         *     <li>using HTTP-ORM library like <a href="https://github.com/OpenFeign/feign">Open-Feign</a>;</li>
         *     <li>executing command-line tool <a href="https://github.com/cli/cli">{@code gh}</a></li>
         * </ul>
         * <hr/>
         * At the moment only {@link GithubApiFeign.FactoryImpl} factory is ready
         * and the static method {@link #feignFactory()} is recommended to use.
         *
         * @return the instance of {@link GithubApi}
         */
        public abstract GithubApi create();

        /**
         * By convention, the name of GitHub-package must be the dot{@code '.'}-concatenating values
         * of maven-project group and maven-project artifact - so, this method calculates that.
         *
         * @param mavenProjectGroup maven-project group
         * @param mavenProjectArtifact maven-project artifact
         * @return dot{@code '.'}-concatenating values pf {@code mavenProjectGroup} and {@code mavenProjectArtifact}
         */
        static String mavenPackageName(String mavenProjectGroup, String mavenProjectArtifact) {
            return String.format("%s.%s", mavenProjectGroup, mavenProjectArtifact);
        }
    }
}
