name: latest-info
run-name: ${{ github.actor }} has executed 'log-latest-info.yml' action
on: workflow_dispatch

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
          echo "::group::My title"
          echo "Inside group"
          echo "::endgroup::"
          echo "----------------------------"
          env | sort
          echo "----------------------------"
