package org.krmdemo.techlabs.thtool;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.apache.commons.lang3.StringUtils;
import org.krmdemo.techlabs.core.dump.DumpUtils;
import org.krmdemo.techlabs.core.utils.PropertiesUtils;

import java.util.NavigableMap;

/**
 * This class represents a helper-object to work with maven-properties,
 * which is available from <b>{@code th-tool}</b>-templates by name {@code mh}.
 * <hr/>
 * It encapsulates the logic of incrementing the version of maven-project
 * during internal and public releases, which is usually performed by
 * <a href="https://maven.apache.org/maven-release/maven-release-plugin/">Maven Release Plugin</a>
 * with its goals:<ul>
 *     <li><a href="https://maven.apache.org/maven-release/maven-release-plugin/prepare-mojo.html">
 *         release:prepare
 *     </a></li>
 *     <li><a href="https://maven.apache.org/maven-release/maven-release-plugin/prepare-mojo.html">
 *         release:prepare-with-pom
 *     </a></li>
 * </ul>
 */
@JsonPropertyOrder(alphabetic = true)
public class MavenHelper {

    /**
     * Default path to properties-resource that is generated by <b>{@code properties-maven-plugin}</b>
     * and corresponds to its {@code outputFile} configuration parameter.
     */
    public final static String RESOURCE_PATH__MVN_PROPS =
        "/META-INF/maven/maven-project.properties";

    private final static String PROP_NAME__PROJECT_ARTIFACT = "maven-project.artifact";
    private final static String PROP_NAME__PROJECT_VERSION = "maven-project.version";

    private final static String PROP_NAME__MAJOR_VERSION = "parsedVersion.majorVersion";
    private final static String PROP_NAME__MINOR_VERSION = "parsedVersion.minorVersion";
    private final static String PROP_NAME__INCREMENTAL_VERSION = "parsedVersion.incrementalVersion";
    private final static String PROP_NAME__VERSION_QUALIFIER = "parsedVersion.qualifier";

    private final String resourcePathMvnProps;
    private final NavigableMap<String, String> mvnPropsMap;

    /**
     * Constructor over {@link #RESOURCE_PATH__MVN_PROPS default maven-properties}
     */
    public MavenHelper() {
        this(RESOURCE_PATH__MVN_PROPS);
    }

    /**
     * @param resourcePathMvnProps the path to maven-properties resource
     */
    public MavenHelper(String resourcePathMvnProps) {
        this.resourcePathMvnProps = resourcePathMvnProps;
        this.mvnPropsMap = PropertiesUtils.propsMapResource(resourcePathMvnProps);
    }

    public String getResourcePath() {
        return resourcePathMvnProps;
    }

    /**
     * @return colon({@code ':'})-separated {@link #getProjectArtifact()} and {@link #getCalculatedProjectVersion()}
     */
    public String getProjectName() {
        return getProjectArtifact() + ":" + getCurrentProjectVersion();
    }

    /**
     * @return the same as {@link #getProjectName()}, but dash({@code '-'})-symbol is duplicated like {@code "--"}
     */
    public String getProjectBadgeName() {
        return getProjectName().replace("-", "--");
    }

    /**
     * @return the same as {@link #getProjectName()}, but colon({@code ":"})-symbol is substituted with dash({@code '-'}
     */
    public String getProjectCatalogName() {
        return getProjectName().replace(':', '-');
    }

    /**
     * @return the name of project artifact ({@code "core-utils"})
     */
    public String getProjectArtifact() {
        return mvnPropsMap.get(PROP_NAME__PROJECT_ARTIFACT);
    }

    /**
     * @return the full current version of project in {@code pom.xml} (like {@code 21.04.008-SNAPSHOT})
     */
    public String getCurrentProjectVersion() {
        return mvnPropsMap.get(PROP_NAME__PROJECT_VERSION);
    }

    /**
     * For the project version like {@code 21.04.008-SNAPSHOT} this method returns like {@code 21.04.008}
     *
     * @return the same as {@link #getCurrentProjectVersion()}, but without qualifier
     */
    public String getInternalReleaseVersion() {
        return String.format(INTERNAL_RELEASE_VERSION_FORMAT,
            getMajorVersionAsInt(),
            getMinorVersionAsInt(),
            getIncrementalAsInt()
        );
    }

    /**
     * For the project version like {@code 21.04.008-SNAPSHOT} this method returns like {@code 21.04}
     *
     * @return the same as {@link #getCurrentProjectVersion()}, but without qualifier and incremental version
     */
    public String getPublicReleaseVersion() {
        return String.format(PUBLIC_RELEASE_VERSION_FORMAT,
            getMajorVersionAsInt(),
            getMinorVersionAsInt()
        );
    }

    /**
     * For the project version like {@code 21.04.008-SNAPSHOT} this method returns like {@code 21.05.001-SNAPSHOT}
     *
     * @return calculated from {@link #getCurrentProjectVersion()},
     * by increasing the minor version and reset the incremental version to {@code 1}
     */
    public String getPublicNextVersion() {
        return String.format(SNAPSHOT_VERSION_FORMAT,
            getMajorVersionAsInt(),
            getMinorVersionAsInt() + 1,
            1,
            getVersionQualifier()
        );
    }

    /**
     * For the project version like {@code 21.04.008-SNAPSHOT} this method returns like {@code 21.05.009-SNAPSHOT}
     *
     * @return calculated from {@link #getCurrentProjectVersion()}, by increasing the incremental version
     */
    public String getInternalNextVersion() {
        return String.format(SNAPSHOT_VERSION_FORMAT,
            getMajorVersionAsInt(),
            getMinorVersionAsInt(),
            getIncrementalAsInt() + 1,
            getVersionQualifier()
        );
    }

    /**
     * This property is helpful, when for some reason the value of version in {@code pom.xml} is corrupted.
     *
     * @return in normal scenario exactly the same as {@link #getCurrentProjectVersion}
     */
    public String getCalculatedProjectVersion() {
        return String.format(SNAPSHOT_VERSION_FORMAT,
            getMajorVersionAsInt(),
            getMinorVersionAsInt(),
            getIncrementalAsInt(),
            getVersionQualifier()
        );
    }

    /**
     * @return in this project this method must always return the value {@code "21"},
     * which corresponds to the minimal version of JDK this library is built with
     */
    public String getMajorVersion() {
        return mvnPropsMap.getOrDefault(PROP_NAME__MAJOR_VERSION, "21");
    }

    /**
     * @return the value of {@link #getMajorVersion()} as {@link Integer}
     */
    public Integer getMajorVersionAsInt() {
        return Integer.valueOf(getMajorVersion());
    }

    /**
     * @return the minor version corresponds to ordinal number of <b>public release</b>
     */
    public String getMinorVersion() {
        return mvnPropsMap.getOrDefault(PROP_NAME__MINOR_VERSION, "0");
    }

    /**
     * @return the value of {@link #getMinorVersion()} as {@link Integer}
     */
    public Integer getMinorVersionAsInt() {
        return Integer.valueOf(getMinorVersion());
    }

    /**
     * @return the minor version corresponds to the ordinal number of <b>internal release</b>
     * since the last <b>public release</b> (should be {@code 0} right after the public release is performed)
     */
    public String getIncrementalVersion() {
        return mvnPropsMap.getOrDefault(PROP_NAME__INCREMENTAL_VERSION, "0");
    }

    /**
     * @return the value of {@link #getIncrementalVersion()} as {@link Integer}
     */
    public Integer getIncrementalAsInt() {
        return Integer.valueOf(getIncrementalVersion());
    }

    /**
     * @return in this project this method must always return the value {@code "SNAPSHOT"}
     */
    public String getVersionQualifier() {
        String qualifier = mvnPropsMap.get(PROP_NAME__VERSION_QUALIFIER);
        return StringUtils.isBlank(qualifier) ? "SNAPSHOT" : qualifier;
    }

    @Override
    public String toString() {
        return "maven-helper object with properties --> " + DumpUtils.dumpAsJsonTxt(this);
    }

    // --------------------------------------------------------------------------------------------

    /**
     * The format-string of maven-project version that is in development right now:
     * <br/>{@literal <major-version>.<minor-version>.<incremental-version>-<qualifier>}
     */
    final static String SNAPSHOT_VERSION_FORMAT = "%d.%02d.%03d-%s";

    /**
     * The same as {@link #SNAPSHOT_VERSION_FORMAT}, but without qualifier-suffix.
     */
    final static String INTERNAL_RELEASE_VERSION_FORMAT = "%d.%02d.%03d";

    /**
     * The same as {@link #INTERNAL_RELEASE_VERSION_FORMAT}, but without incremental version.
     */
    final static String PUBLIC_RELEASE_VERSION_FORMAT = "%d.%02d";

}
