package org.krmdemo.techlabs.thtool.helpers;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.krmdemo.techlabs.opentest4j.OpenTest4jHelper;
import org.krmdemo.techlabs.thtool.ThymeleafTool;
import org.krmdemo.techlabs.thtool.ThymeleafToolCtx;
import org.opentest4j.reporting.tooling.core.htmlreport.DefaultHtmlReportWriter;

import java.nio.file.Path;
import java.util.Objects;
import java.util.function.Consumer;

import static org.krmdemo.techlabs.thtool.helpers.GithubBadgeHelper.LOGO_SLUG_NAME__GIT_HUB;

/**
 * This class represents a <b>{@code th-tool}</b>-helper to work with "GitHub-Packages"-artifactory
 * (where the artifacts of INTERNAL-release are deployed) and "Maven-Central Repository"-artifactory
 * (where the artifacts of PUBLIC-release are deployed. This helper is responsible just for rendering
 * the proper links to those external resources per each version that corresponds to {@link VersionTag}.
 * <hr/>
 * The properties of this helper are available from <b>{@code th-tool}</b>-templates by name {@code ah}.
 * <br/>TODO: to be implemented !!!
 *
 * @see <a href="https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages">
 *     GitHub Packages
 * </a>
 * @see <a href="https://central.sonatype.com/">
 *     Maven Central Repository
 * </a>
 */
public class ArtifactoryHelper {

    /**
     * The name of <b>{@code th-tool}</b>-variable for helper-object {@link ArtifactoryHelper}
     */
    public static final String VAR_NAME__HELPER = "ah";

    /**
     * The name of <i>GH-Package</i> that is used to distribute <b>core-utils</b>-library
     * via <a href="https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages">
     *     GitHub Packages
 *     </a>
     */
    public static final String GH_PACkAGE_NAME = "io.github.krm-demo.core-utils";

    /**
     * The ID of <i>GH-Package</i> with name {@value GH_PACkAGE_NAME}, that is hardcoded here,
     * but it could be obtained via {@code gh api} or using <i>GH-workflow</i> {@code misc--gh-packages.yml}.
     */
    public static final String GH_PACkAGE_ID = "2631343";

    /**
     * URL to the root page of <i>GH-Package</i> with ID {@value GH_PACkAGE_ID}, that is hardcoded here,
     * but it could be obtained via {@code gh api} or using <i>GH-workflow</i> {@code misc--gh-packages.yml}.
     */
    public static final String GH_PACkAGE_HTML_URL = "https://github.com/krm-demo/core-utils/packages/" + GH_PACkAGE_ID;

    /**
     * @param ttCtx <b>{@code th-tool}</b>-context to wrap
     * @return an instance of {@link ArtifactoryHelper} for unit-tests
     */
    public static ArtifactoryHelper fromCtxLazy(ThymeleafToolCtx ttCtx) {
        ArtifactoryHelper helper = fromCtx(ttCtx);
        if (helper == null) {
            ArtifactoryHelper.register(ttCtx);
            GithubBadgeHelper.register(ttCtx);
            GithubHelper.register(ttCtx);
            MavenHelper.register(ttCtx);
            helper = fromCtx(ttCtx);
        }
        return helper;
    }

    /**
     * A factory-method that returns an instance of {@link ArtifactoryHelper}
     * that was previously registered with {@link #register(ThymeleafToolCtx)}.
     *
     * @param ttCtx <b>{@code th-tool}</b>-context to wrap
     * @return an instance of {@link OpenTest4jHelper} for access from other helpers
     */
    public static ArtifactoryHelper fromCtx(ThymeleafToolCtx ttCtx) {
        return ttCtx.typedVar(VAR_NAME__HELPER, ArtifactoryHelper.class);
    }

    /**
     * Context-registering method of functional type {@link Consumer Consumer&lt;ThymeleafToolCtx&gt;}.
     * Should be used when initializing the instance of {@link ThymeleafTool},
     * which allows to decouple the dependencies between <b>{@code th-tool}</b> and helper-objects.
     *
     * @param ttCtx <b>{@code th-tool}</b>-context to register this helper in
     */
    public static void register(ThymeleafToolCtx ttCtx) {
        ArtifactoryHelper helper = new ArtifactoryHelper(ttCtx);
        ttCtx.setVariable(VAR_NAME__HELPER, helper);
    }

    private final ThymeleafToolCtx ttCtx;
    private ArtifactoryHelper(ThymeleafToolCtx ttCtx) {
        this.ttCtx = Objects.requireNonNull(ttCtx);
    }

    // --------------------------------------------------------------------------------------------

    /**
     * A helper-property to be inserted at <b>{@code th-tool}</b>-template in order to render
     * HTML-badge to the test-report that was generated by {@link DefaultHtmlReportWriter opentest4j-library}
     * {@snippet : [(${ ah.badgeHtml })] }
     * <hr/>
     * Such badge is present at main 'Overview' JavaDoc-page
     *
     * @return HTML-badge to the test-results report
     *         that was generated by {@link DefaultHtmlReportWriter opentest4j-library}
     */
    @JsonIgnore
    public String getBadgeGHPkgLongHtml() {
        return String.format("""
            <a href="%s">
              <img alt="a badge to GH-Package '%s'" src="%s" />
            </a>""",
            GH_PACkAGE_HTML_URL,
            GH_PACkAGE_NAME,
            getBadgeGHPkgLongUrl());
    }

    /**
     * A helper-property to be inserted at <b>{@code th-tool}</b>-template in order to render
     * the long GitHub-Markdown'-badge to the GH-Package {@value GH_PACkAGE_NAME}:
     * {@snippet : [(${ ah.badgeGHPkgLongMD })] }
     *
     * @return long GitHub-Markdown'-badge to the GH-Package {@value GH_PACkAGE_NAME}
     */
    public String getBadgeGHPkgLongMD() {
        return String.format(
            "[![GitHub-Packages long](%s)](%s)",
            getBadgeGHPkgLongUrl(),
            GH_PACkAGE_HTML_URL);
    }

    /**
     * A helper-property to be inserted at <b>{@code th-tool}</b>-template in order to render
     * the short GitHub-Markdown'-badge to the GH-Package {@value GH_PACkAGE_NAME}:
     * {@snippet : [(${ ah.badgeGHPkgShortMD })] }
     *
     * @return short GitHub-Markdown'-badge to the GH-Package {@value GH_PACkAGE_NAME}
     */
    public String getBadgeGHPkgShortMD() {
        return String.format(
            "[![GitHub-Packages short](%s)](%s \"GH-Package '%s'\")",
            getBadgeGHPkgShortUrl(),
            GH_PACkAGE_HTML_URL,
            GH_PACkAGE_NAME);
    }

    /**
     * @return the URL to the long badge-image for the GH-Package {@value GH_PACkAGE_NAME}
     */
    public String getBadgeGHPkgLongUrl() {
        GithubBadgeHelper gbh = GithubBadgeHelper.fromCtx(ttCtx);
        return gbh.badgeUrlShiedsIO(GH_PACkAGE_NAME, null,
            "b0e0e6", // <-- this color is called "PowderBlue" at https://htmlcolorcodes.com/color-names/
            LOGO_SLUG_NAME__GIT_HUB,"white", "black");
    }

    /**
     * @return the URL to the long badge-image for the GH-Package {@value GH_PACkAGE_NAME}
     */
    public String getBadgeGHPkgShortUrl() {
        GithubBadgeHelper gbh = GithubBadgeHelper.fromCtx(ttCtx);
        return gbh.badgeUrlShiedsIO("GH-Packages", null,
            "b0e0e6", // <-- this color is called "PowderBlue" at https://htmlcolorcodes.com/color-names/
            LOGO_SLUG_NAME__GIT_HUB,"white", "black");
    }
}
