package org.krmdemo.techlabs.thtool.helpers;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.krmdemo.techlabs.opentest4j.OpenTest4jHelper;
import org.krmdemo.techlabs.thtool.ThymeleafTool;
import org.krmdemo.techlabs.thtool.ThymeleafToolCtx;
import org.opentest4j.reporting.tooling.core.htmlreport.DefaultHtmlReportWriter;

import java.nio.file.Path;
import java.util.Objects;
import java.util.function.Consumer;

/**
 * This class represents a <b>{@code th-tool}</b>-helper to work with "GitHub-Packages"-artifactory
 * (where the artifacts of INTERNAL-release are deployed) and "Maven-Central Repository"-artifactory
 * (where the artifacts of PUBLIC-release are deployed. This helper is responsible just for rendering
 * the proper links to those external resources per each version that corresponds to {@link VersionTag}.
 * <hr/>
 * The properties of this helper are available from <b>{@code th-tool}</b>-templates by name {@code ah}.
 * <br/>TODO: to be implemented !!!
 *
 * @see <a href="https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages">
 *     GitHub Packages
 * </a>
 * @see <a href="https://central.sonatype.com/">
 *     Maven Central Repository
 * </a>
 */
public class ArtifactoryHelper {

    /**
     * The name of <b>{@code th-tool}</b>-variable for helper-object {@link ArtifactoryHelper}
     */
    public static final String VAR_NAME__HELPER = "ah";

    /**
     * @param ttCtx <b>{@code th-tool}</b>-context to wrap
     * @return an instance of {@link ArtifactoryHelper} for unit-tests
     */
    public static ArtifactoryHelper fromCtxLazy(ThymeleafToolCtx ttCtx) {
        ArtifactoryHelper helper = fromCtx(ttCtx);
        if (helper == null) {
            ArtifactoryHelper.register(ttCtx);
            GithubBadgeHelper.register(ttCtx);
            GithubHelper.register(ttCtx);
            MavenHelper.register(ttCtx);
            helper = fromCtx(ttCtx);
        }
        return helper;
    }

    /**
     * A factory-method that returns an instance of {@link ArtifactoryHelper}
     * that was previously registered with {@link #register(ThymeleafToolCtx)}.
     *
     * @param ttCtx <b>{@code th-tool}</b>-context to wrap
     * @return an instance of {@link OpenTest4jHelper} for access from other helpers
     */
    public static ArtifactoryHelper fromCtx(ThymeleafToolCtx ttCtx) {
        return ttCtx.typedVar(VAR_NAME__HELPER, ArtifactoryHelper.class);
    }

    /**
     * Context-registering method of functional type {@link Consumer Consumer&lt;ThymeleafToolCtx&gt;}.
     * Should be used when initializing the instance of {@link ThymeleafTool},
     * which allows to decouple the dependencies between <b>{@code th-tool}</b> and helper-objects.
     *
     * @param ttCtx <b>{@code th-tool}</b>-context to register this helper in
     */
    public static void register(ThymeleafToolCtx ttCtx) {
        ArtifactoryHelper helper = new ArtifactoryHelper(ttCtx);
        ttCtx.setVariable(VAR_NAME__HELPER, helper);
    }

    private final ThymeleafToolCtx ttCtx;
    private ArtifactoryHelper(ThymeleafToolCtx ttCtx) {
        this.ttCtx = Objects.requireNonNull(ttCtx);
    }

    // --------------------------------------------------------------------------------------------

    /**
     * A helper-property to be inserted at <b>{@code th-tool}</b>-template in order to render
     * HTML-badge to the test-report that was generated by {@link DefaultHtmlReportWriter opentest4j-library}
     * {@snippet : [(${ ah.badgeHtml })] }
     * <hr/>
     * Such badge is present at main 'Overview' JavaDoc-page
     *
     * @return HTML-badge to the test-results report
     *         that was generated by {@link DefaultHtmlReportWriter opentest4j-library}
     */
    @JsonIgnore
    public String getBadgeGHPackagesHtml() {
        return String.format("""
            <a href="https://krm-demo.github.io/core-utils/%s-%s/open-test-report.html">
              <img alt="a badge to the test-report of the current project-version" src="%s" />
            </a>""",
            GithubHelper.fromCtx(ttCtx).getRepoName(),
            MavenHelper.fromCtx(ttCtx).getCurrentProjectVersion(),
            getBadgeGHPackagesUrl());
    }

    /**
     * A helper-property to be inserted at <b>{@code th-tool}</b>-template in order to render
     * GitHub-Markdown'-badge to the GitHub-project of the current version:
     * {@snippet : [(${ openTest4j.badgeMarkdown })] }
     * <hr/>
     * Such badge is present at root 'README.md'-file of GitHub-project
     *
     * @return GitHub-Markdown'-badge to the test-results report
     *         that was generated by {@link DefaultHtmlReportWriter opentest4j-library}
     */
    public String getBadgeGHPackagesMarkdown() {
        return String.format(
            "[![GitHub-Packages](%s)](https://krm-demo.github.io/core-utils/%s-%s/open-test-report.html)",
            getBadgeGHPackagesUrl(),
            GithubHelper.fromCtx(ttCtx).getRepoName(),
            MavenHelper.fromCtx(ttCtx).getCurrentProjectVersion());
    }

    /**
     * @return the URL to the badge-image for the test-results report
     *         that was generated by {@link DefaultHtmlReportWriter opentest4j-library}
     */
    public String getBadgeGHPackagesUrl() {
        GithubBadgeHelper gbh = GithubBadgeHelper.fromCtx(ttCtx);
        return gbh.badgeUrlShiedsIO("test-results", "Open-Test-4j", "blue",
            //"b0e0e6", // <-- this color is called "PowderBlue" at https://htmlcolorcodes.com/color-names/
            Path.of(".github/images/opentest4j/opentest4j-logo--48.png").toFile(),
            "f8981d", // <-- this color corresponds "--selected-background-color" CSS-variable at JavDoc-site
            "4D7A97" // <-- this color corresponds "--navbar-background-color" CSS-variable at JavDoc-site
        );
    }
}
