name: latest-info
run-name: ${{ github.actor }} has executed 'misc--th-tool-help.yml' ##${{ github.run_number }}
on: workflow_dispatch

jobs:

  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the latest version of repo in '${{ github.ref }}'"
        uses: actions/checkout@v4
      - name: Set up JDK 21 (Amazon Corretto)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          check-latest: true
          cache: 'maven'

      - run: .github/th-tool-help.sh
