name: gh-pages
run-name: ${{ github.actor }} has executed 'misc--gh-pages.yml' №${{ github.run_number }}
on: workflow_dispatch

jobs:

  main-build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the 'main'-branch of repo '${{ github.ref }}' into './main-branch'"
        uses: actions/checkout@v4
        with:
          ref: main
          path: main-branch

      - name: "Set up JDK 21 (Amazon Corretto)"
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          check-latest: true
          cache: 'maven'
          cache-dependency-path: main-branch/pom.xml

      - name: "Setup JBang"
        uses: jbangdev/setup-jbang@main

      - name: "Demonstrate the basic remote JBang's script 'properties@jbangdev'"
        run: jbang properties@jbangdev 'java.v' 'java.r' 'java.s' 'sun.*' 'user.*'

      - name: "Dump Environment-Variables into '.github/th-vars'-dir"
        run: |
          # dump the output of './src/scripts/jbang/DumpEnvVars.java' into JSON-file
          cd main-branch          
          echo "Current directory is $(pwd)"
          jbang --quiet src/scripts/jbang/DumpEnvVars.java
          jbang --quiet src/scripts/jbang/DumpEnvVars.java > .github/th-vars/var-envVars.json

      - name: "Dump Java System-Properties into '.github/th-vars'-dir"
        run: |
          # dump the output of './src/scripts/jbang/DumpSysProps.java' into JSON-file
          cd main-branch          
          echo "Current directory is $(pwd)"
          jbang --quiet src/scripts/jbang/DumpSysProps.java
          jbang --quiet src/scripts/jbang/DumpSysProps.java > .github/th-vars/var-sysProps.json

      - name: "Dump Git-Hub context into '.github/th-vars'-dir"
        run: |
          # dump the value of {{ github }} into JSON-file
          cd main-branch          
          echo "Current directory is $(pwd)"
          echo '${{ toJson(github) }}' > .github/th-vars/var-github.json

      - name: "Dump 'secrets' context into '.github/th-vars'-dir"
        run: |
          # dump the value of {{ secrets }} into JSON-file
          cd main-branch          
          echo "Current directory is $(pwd)"
          echo '${{ toJson(secrets) }}' > .github/th-vars/var-secrets.json

      - name: "Perform the build and install using 'Apache Maven'"
        run: |
          # build and install to local maven repository
          cd main-branch          
          echo "Current directory is $(pwd)"
          mvn -B clean install

      - name: "Checkout the 'main'-branch of repo '${{ github.ref }}' into './main-branch'"
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages-branch

      - name: "Verify that total working tree contains two branches correctly"
        run: tree

      - name: "Create, commit and push some test text-file into 'gh-pages'"
        run: |
          # build and install to local maven repository
          echo 'created by GitHub-Workflow "'$GITHUB_WORKFLOW'" at '$(date) > gh-pages-branch/a.txt
          tree gh-pages-branch
          cd gh-pages-branch
          git status
          git add .
          git commit -m "add the test text-file a.txt as a result of GitHub-Workflow '$GITHUB_WORKFLOW' #$GITHUB_RUN_NUMBER"
          git push origin gh-pages
          echo "That's it "'!!!'
